/*
 * This source file was generated by the Gradle 'init' task
 */
package grade;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

       System.out.println("Input your score: ");
        int score = scan.nextInt();

        String grade;
        if (score >= 80) {
            grade = "A";
        } else if (score >= 75) {
            grade = "B+";
        } else if (score >= 70) {
            grade = "B";
        } else if (score >= 65) {
            grade = "C+";
        } else if (score >= 60) {
            grade = "C";
        } else if (score >= 55) {
            grade = "D+";
        } else if (score >= 50) {
            grade = "D";
        } else {
            grade = "F";  // This will handle all scores less than 50
        }
        System.out.println("Your grade is: " + grade);
    }
}
