/*
 * This source file was generated by the Gradle 'init' task
 */
package factorial;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter a number: ");
        int number = scanner.nextInt();

        scanner.close();

       int fact = 1;
       for(int i = 1; i <= number; i++){
            System.out.println(i + " ! = " + fact);
            fact += fact * i;
        }  
    }
}