/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment01;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Scanner scanner = new Scanner(System.in);
        System.out.println("Input value A: ");
        int A = scanner.nextInt(); // รับค่าจำนวนเต็ม 3 จำนวน
        System.out.println("Input value B: ");
        int B = scanner.nextInt();
        System.out.println("Input value C: ");
        int C = scanner.nextInt();

        if (A >= B && A >= B) {
            System.out.println("Max value  is A: ");
        } else if (B >= A && B >= C) {
            System.out.println("Max value is B: ");
        } else
            System.out.println("Max value is C: ");

        scanner.close();

    }

}
