/*
 * This source file was generated by the Gradle 'init' task
 */
package sequence;

public class App {
    public String getGreeting() {
        return "";
    }

    /**
     * @param args
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // 8.1 For loop
        System.out.println("8.1 Sequence for loop");
        int sum = 0;

        for (int i = 1; i <= 10; i++) {
            System.out.print(i + " ");
            sum += i;
        }
        System.out.println("\nTotal : " + sum);

        // 8.1 while loop
        System.out.println("\n8.1 Sequence while loop");
        int u = 10;
        int sum1 = 0;
        while (u >= 1) {
            System.out.print(u + " ");
            sum1 += u;
            u--;
        }
        System.out.println("\nTotal = " + sum1);

        // 8.2 For loop
        System.out.println("\n8.2 Sequence for loop");
        int sum2 = 0;

        for (int o = 1; o <= 19; o += 2) {
            System.out.print(o + " ");
            sum2 += o;
        }
        System.out.println("\nTotal = " + sum2);

        // 8.2 while loop
        System.out.println("\n8.2  while loop");
        int i3 = 1;
        int sum3 = 0;

        while (i3 <= 19) {
            System.out.print(i3 + " ");
            sum3 += i3;
            i3 += 2;
        }
        System.out.println("\nTotal = " + sum3);
        
        // 8.3 For loop
        System.out.println("\n8.3  for loop");
        int totalSum = 0;
        
        for (int i = 0, num4 = 1; num4 <= 19; num4 += 2, i++) {
            if (i % 2 == 1) {  
                System.out.print(-num4 + " ");
                totalSum -= num4;
            } else {
                System.out.print(num4 + " ");
                totalSum += num4;
            }
        }
        System.out.println("\nTotal = " + totalSum);

        // 8.3  while loop
        System.out.println("\n8.3  while loop");
        int y = 1;
        int sum5 = 0;
        boolean toggleSign = true;
        while (y <= 19) {
            if (toggleSign) {
                System.out.print(y + " ");
                sum5 += y;
            } else {
                System.out.print(-y + " ");
                sum5 -= y;
            }
            toggleSign = !toggleSign;
            y += 2;
        }
        System.out.println("\nTotal = " + sum5);
    }
}
    

